"""add_eis_schema_tables

Revision ID: 0c0cbee2a179
Revises: df8aad89947d
Create Date: 2026-10-03 16:28:27.537060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0cbee2a179'
down_revision: Union[str, None] = 'df8aad89947d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS eis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eis_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_token', sa.String(length=500), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eis_sessions')),
    schema='eis'
    )
    op.create_index(op.f('ix_eis_eis_sessions_is_active'), 'eis_sessions', ['is_active'], unique=False, schema='eis')
    op.create_table('eis_transmissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submit_id', sa.String(length=100), nullable=False),
    sa.Column('parent_transmission_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ACKNOWLEDGED', 'FAILED', 'PARTIAL', name='eistransmissionstatus'), nullable=False),
    sa.Column('ack_id', sa.String(length=200), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('process_status_code', sa.String(length=2), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_request', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_transmission_id'], ['eis.eis_transmissions.id'], name=op.f('fk_eis_transmissions_parent_transmission_id_eis_transmissions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eis_transmissions')),
    schema='eis'
    )
    op.create_index(op.f('ix_eis_eis_transmissions_status'), 'eis_transmissions', ['status'], unique=False, schema='eis')
    op.create_index(op.f('ix_eis_eis_transmissions_submit_id'), 'eis_transmissions', ['submit_id'], unique=True, schema='eis')
    op.create_table('eis_transmission_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transmission_id', sa.UUID(), nullable=False),
    sa.Column('eis_unique_id', sa.String(length=24), nullable=False),
    sa.Column('comp_invoice_id', sa.String(length=50), nullable=False),
    sa.Column('result_status', sa.Enum('SUCCESS', 'SYNTAX_ERROR', 'RULE_ERROR', name='eisresultstatus'), nullable=False),
    sa.Column('fail_reason_code', sa.String(length=10), nullable=True),
    sa.Column('fail_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transmission_id'], ['eis.eis_transmissions.id'], name=op.f('fk_eis_transmission_items_transmission_id_eis_transmissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eis_transmission_items')),
    schema='eis'
    )
    op.create_index(op.f('ix_eis_eis_transmission_items_eis_unique_id'), 'eis_transmission_items', ['eis_unique_id'], unique=False, schema='eis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eis_eis_transmission_items_eis_unique_id'), table_name='eis_transmission_items', schema='eis')
    op.drop_table('eis_transmission_items', schema='eis')
    op.drop_index(op.f('ix_eis_eis_transmissions_submit_id'), table_name='eis_transmissions', schema='eis')
    op.drop_index(op.f('ix_eis_eis_transmissions_status'), table_name='eis_transmissions', schema='eis')
    op.drop_table('eis_transmissions', schema='eis')
    op.drop_index(op.f('ix_eis_eis_sessions_is_active'), table_name='eis_sessions', schema='eis')
    op.drop_table('eis_sessions', schema='eis')
    op.execute("DROP SCHEMA IF EXISTS eis CASCADE")
    # ### end Alembic commands ###
