"""not_required_compliance_invoice_id_with_optional_value

Revision ID: 115db0f2db89
Revises: 0c0cbee2a179
Create Date: 2026-10-08 09:18:47.463450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115db0f2db89'
down_revision: Union[str, None] = '0c0cbee2a179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eis_transmission_items', 'comp_invoice_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='eis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eis_transmission_items', 'comp_invoice_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='eis')
    # ### end Alembic commands ###
