"""add_user_code_to_users_table

Revision ID: f02d51fd612e
Revises: 115db0f2db89
Create Date: 2026-10-09 21:00:21.072066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02d51fd612e'
down_revision: Union[str, None] = '115db0f2db89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE IF NOT EXISTS auth.user_code_seq START WITH 1 INCREMENT BY 1;")
    op.add_column(
        'users',
        sa.Column(
            'user_code',
            sa.String(length=20),
            server_default=sa.text("'USR-' || lpad(nextval('auth.user_code_seq')::text, 5, '0')"),
            nullable=False,
        ),
        schema='auth',
    )
    op.create_index(op.f('ix_auth_users_user_code'), 'users', ['user_code'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_user_code'), table_name='users', schema='auth')
    op.drop_column('users', 'user_code', schema='auth')
    op.execute("DROP SEQUENCE IF EXISTS auth.user_code_seq;")
    # ### end Alembic commands ###
