"""add_user_permissions_and_change_requests

Revision ID: ffca0bf82523
Revises: f02d51fd612e
Create Date: 2026-10-10 16:27:22.936229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ffca0bf82523'
down_revision: Union[str, None] = 'f02d51fd612e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

rbac_change_request_status = postgresql.ENUM(
    'PENDING', 'APPROVED', 'REJECTED',
    name='rbacchangerequeststatus',
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    rbac_change_request_status.create(op.get_bind(), checkfirst=True)

    op.create_table('rbac_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('requested_payload', sa.String(length=2000), nullable=False),
    sa.Column('status', rbac_change_request_status, nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['auth.users.id'], name=op.f('fk_rbac_change_requests_requested_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['auth.users.id'], name=op.f('fk_rbac_change_requests_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_role_id'], ['auth.roles.id'], name=op.f('fk_rbac_change_requests_target_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['auth.users.id'], name=op.f('fk_rbac_change_requests_target_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_change_requests')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_rbac_change_requests_status'), 'rbac_change_requests', ['status'], unique=False, schema='auth')
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['auth.users.id'], name=op.f('fk_user_permissions_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], name=op.f('fk_user_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_user_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name=op.f('pk_user_permissions')),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions', schema='auth')
    op.drop_index(op.f('ix_auth_rbac_change_requests_status'), table_name='rbac_change_requests', schema='auth')
    op.drop_table('rbac_change_requests', schema='auth')
    rbac_change_request_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

